# =====================================================
# dbt project - skeleton (Sprint 1)
# Modelos seraco preenchidos na Sprint 4
# =====================================================

name: 'elt_pipeline'
version: '0.1.0'
config-version: 2

profile: 'elt_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  elt_pipeline:
    +materialized: view
    silver:
      +schema: silver
      +materialized: incremental
    gold:
      +schema: gold
      +materialized: table
    platinum:
      +schema: platinum
      +materialized: table
