{% macro clean_projeto_sup(source_relation, empresa_nome) %}
select
    -- Chaves primárias e de negócios
    try_cast(id_empresa as bigint) as id_empresa,
    try_cast(id_unidade as bigint) as id_unidade,
    try_cast(id_projeto as bigint) as id_projeto,
    nullif(try_cast(id_projeto_pai as bigint), 0) as id_projeto_pai,
    nullif(try_cast(id_safra as bigint), 0) as id_safra,
    nullif(try_cast(id_centro_custo as bigint), 0) as id_centro_custo,
    nullif(try_cast(id_conta as bigint), 0) as id_conta,
    nullif(try_cast(id_analitico as bigint), 0) as id_analitico,

    -- Datas e Horas
    nullif(try_cast(ano as int), 0) as ano,
    nullif(try_cast(mes as int), 0) as mes,
    case when data_abertura = '1900-01-01' then null else try_cast(data_abertura as date) end as data_abertura,
    case when data_encerramento = '1900-01-01' then null else try_cast(data_encerramento as date) end as data_encerramento,
    case when data_previsao_encerramento = '1900-01-01' then null else try_cast(data_previsao_encerramento as date) end as data_previsao_encerramento,
    case when data_cadastro_projeto = '1900-01-01' then null else try_cast(data_cadastro_projeto as date) end as data_cadastro_projeto,
    nullif(try_cast(hora_cadstro_projeto as int), 0) as hora_cadastro_projeto,
    case when data_desbloqueio_seq1 = '1900-01-01' then null else try_cast(data_desbloqueio_seq1 as date) end as data_desbloqueio_seq1,
    case when data_desbloqueio_seq2 = '1900-01-01' then null else try_cast(data_desbloqueio_seq2 as date) end as data_desbloqueio_seq2,
    case when data_desbloqueio_seq3 = '1900-01-01' then null else try_cast(data_desbloqueio_seq3 as date) end as data_desbloqueio_seq3,
    case when data_desbloqueio_seq4 = '1900-01-01' then null else try_cast(data_desbloqueio_seq4 as date) end as data_desbloqueio_seq4,
    case when data_desbloqueio_seq5 = '1900-01-01' then null else try_cast(data_desbloqueio_seq5 as date) end as data_desbloqueio_seq5,
    case when data_desbloqueio_seq6 = '1900-01-01' then null else try_cast(data_desbloqueio_seq6 as date) end as data_desbloqueio_seq6,
    nullif(try_cast(hora_desbloqueio_seq1 as int), 0) as hora_desbloqueio_seq1,
    nullif(try_cast(hora_desbloqueio_seq2 as int), 0) as hora_desbloqueio_seq2,
    nullif(try_cast(hora_desbloqueio_seq3 as int), 0) as hora_desbloqueio_seq3,
    nullif(try_cast(hora_desbloqueio_seq4 as int), 0) as hora_desbloqueio_seq4,
    nullif(try_cast(hora_desbloqueio_seq5 as int), 0) as hora_desbloqueio_seq5,
    nullif(try_cast(hora_desbloqueio_seq6 as int), 0) as hora_desbloqueio_seq6,
    case when data_atualizao_dw = '1900-01-01' then null else try_cast(data_atualizao_dw as date) end as data_atualizacao_dw,
    case when data_criacao = '1900-01-01' then null else try_cast(data_criacao as date) end as data_criacao,

    -- Descrições e Textos
    nullif(trim(importancia), '') as importancia,
    nullif(trim(gravidade), '') as gravidade,
    nullif(trim(justificativa), '') as justificativa,
    nullif(trim(informacoes_adicionais), '') as informacoes_adicionais,
    nullif(trim(descricao_projeto), '') as descricao_projeto,
    nullif(trim(usuario), '') as usuario,
    nullif(trim(usuario_aprovador_seq1), '') as usuario_aprovador_seq1,
    nullif(trim(usuario_aprovador_seq2), '') as usuario_aprovador_seq2,
    nullif(trim(usuario_aprovador_seq3), '') as usuario_aprovador_seq3,
    nullif(trim(usuario_aprovador_seq4), '') as usuario_aprovador_seq4,
    nullif(trim(usuario_aprovador_seq5), '') as usuario_aprovador_seq5,
    nullif(trim(usuario_aprovador_seq6), '') as usuario_aprovador_seq6,
    nullif(trim(observacao_aprovacao_seq1), '') as observacao_aprovacao_seq1,
    nullif(trim(observacao_aprovacao_seq2), '') as observacao_aprovacao_seq2,
    nullif(trim(observacao_aprovacao_seq3), '') as observacao_aprovacao_seq3,
    nullif(trim(observacao_aprovacao_seq4), '') as observacao_aprovacao_seq4,
    nullif(trim(observacao_aprovacao_seq5), '') as observacao_aprovacao_seq5,
    nullif(trim(observacao_aprovacao_seq6), '') as observacao_aprovacao_seq6,
    nullif(trim(upper(situacao)), '') as situacao,
    nullif(trim(upper(lavoura)), '') as lavoura,
    nullif(trim(upper(status_projeto)), '') as status_projeto,
    nullif(trim(upper(custo_fixo)), '') as custo_fixo,
    nullif(trim(usuario_envolvido1), '') as usuario_envolvido1,
    nullif(trim(usuario_envolvido2), '') as usuario_envolvido2,
    nullif(trim(usuario_envolvido3), '') as usuario_envolvido3,
    nullif(trim(usuario_envolvido4), '') as usuario_envolvido4,
    nullif(trim(usuario_envolvido5), '') as usuario_envolvido5,
    nullif(trim(fase), '') as fase,
    nullif(trim(urgencia), '') as urgencia,
    nullif(trim(objetivo), '') as objetivo,
    nullif(trim(alinhamento_estrategico), '') as alinhamento_estrategico,
    nullif(trim(upper(credita_pis_cofins)), '') as credita_pis_cofins,
    nullif(trim(nome_projeto), '') as nome_projeto,

    -- Valores Numéricos / Financeiros
    nullif(try_cast(sequencia_aprovacao_atual as int), 0) as sequencia_aprovacao_atual,
    nullif(try_cast(valor_previsto_seq1 as numeric(17,2)), 0) as valor_previsto_seq1,
    nullif(try_cast(valor_previsto_seq2 as numeric(17,2)), 0) as valor_previsto_seq2,
    nullif(try_cast(valor_previsto_seq3 as numeric(17,2)), 0) as valor_previsto_seq3,
    nullif(try_cast(valor_previsto_seq4 as numeric(17,2)), 0) as valor_previsto_seq4,
    nullif(try_cast(valor_previsto_seq5 as numeric(17,2)), 0) as valor_previsto_seq5,
    nullif(try_cast(valor_previsto_seq6 as numeric(17,2)), 0) as valor_previsto_seq6,
    nullif(try_cast(valor_aprovado_ordem_compra as numeric(17,2)), 0) as valor_aprovado_ordem_compra,
    nullif(try_cast(valor_previsto as numeric(17,2)), 0) as valor_previsto,
    nullif(try_cast(valor_realizado as numeric(17,2)), 0) as valor_realizado,

    -- Campo de origem da empresa
    '{{ empresa_nome }}' as empresa
from {{ source_relation }}
{% endmacro %}
